# Don't print a new line at the start of the prompt
add_newline = false

# Use custom format
format = """
[â•­â”€](white)$username in $directory$git_branch$git_status$nodejs$golang
[â•°â”€](white)$character """

right_format = """$cmd_duration"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "bold bright-yellow"
format = "[$user]($style)"
disabled = false

# Hostname settings
[hostname]
ssh_only = true

# Directory indicator
[directory]
read_only = "ğŸ”’"
style = "bold bright-blue"
read_only_style = "red"
truncation_length = 8
truncation_symbol = ""
format = "[$read_only]($read_only_style)[$path]($style) "
disabled = false

# Package Version Config
[package]
disabled=true

# git settings
[git_branch]
symbol = "ğŸŒ± "

# cmd_duration config
[cmd_duration]
show_milliseconds = true
style = "bold yellow"
format = "took [$duration]($style)"

# Charakter config
[character]
format = "$symbol"
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[â®](bold green)"
disabled = false

[nodejs]
symbol = "ğŸ¢ "

[aws]
symbol = "â˜ï¸  "

[golang]
symbol = "ğŸ§ "
